sudo: required

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
      dist: xenial

script:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update
  - sudo apt-get install git
  - if ./buildTools/runTools.sh travis | grep "Error:"; then exit 1; fi